name: psoria-bioinf
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - requests
  - tqdm
  - networkx
  - rdkit
  - pip:
    - gseapy
    - mygene
